name: Test Installation

on:
  push:
    branches: [ pysweph, dev ]
  pull_request:
    branches: [ pysweph, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Build Source Distribution
        run: uv build --sdist

      - name: Verify C-Extension
        run: uv run python -c "import swisseph; print('Successfully loaded extension')"
